version: '3'
volumes:
  avalanche-data:
  avalanche-ipcs:
networks:
  services:
    external:
      name: ortelius_services
services:
  indexer: &ortelius-app
    image: "ortelius-local"
    command: ["stream", "indexer", "-c", "/opt/config.json"]
    networks:
      - services
    external_links:
      - mysql
    volumes:
      - avalanche-ipcs:/tmp
      - ./config.standalone.json:/opt/config.json
    restart: on-failure
  api:
    <<: *ortelius-app
    command: ["api", "-c", "/opt/config.json"]
    ports:
      - 8080:8080
